# Generated by Django 6.0 on 2025-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='diastolic_bp',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='systolic_bp',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
