# Generated by Django 6.0 on 2025-12-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='ehealth.patient'),
        ),
    ]
