# Generated by Django 6.0 on 2025-12-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0002_remove_vitalsign_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='diastolic_bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='systolic_bp',
            field=models.IntegerField(null=True),
        ),
    ]
