# Generated by Django 6.0 on 2025-12-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0003_alter_consultation_appointment'),
    ]

    operations = [
    ]
